kind = "api"
previewPath = "/"
title = "Flask App"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 5000
name = "Flask App"
paths = ["/"]

[services.development]
run = "/home/runner/workspace/.venv/bin/python /home/runner/workspace/main.py"
