kind = "api"
previewPath = "/"
title = "Telegram Pro"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 3000
name = "Telegram Pro"
paths = ["/", "/api", "/socket.io"]

[services.development]
run = "cd /home/runner/workspace && pnpm dev"
